export const mocoData = [
  {
    name : 'Jacket',
    price : '$ 120',
    category : 'firstpage',
    color : ['#3B6392', '#B0C3C7', ' #BFC3C8'],
    size : ['XS', 'S', 'M', 'L', 'XL'],
    mobileUrl : `../../img/model-1.jpg`,
    tableUrl : `../../img/table-model-1.jpg`,
    dcUrl : `../../img/model-dc-1.jpg`,
  },
  {
    name : 'Overalls',
    price : '$ 140',
    category : 'firstpage',
    color : ['#3B6392', '#B0C3C7', ' #BFC3C8'],
    size : ['XS', 'S', 'M', 'L', 'XL'],
    mobileUrl : `../../img/model-2.jpg`,
    tableUrl : `../../img/table-model-2.jpg`,
    dcUrl : `../../img/model-dc-2.jpg`,
  },
  {
    name : 'Jacket',
    price : '$ 90',
    category : 'firstpage',
    color : ['#3B6392', '#B0C3C7', ' #BFC3C8'],
    size : ['XS', 'S', 'M', 'L', 'XL'],
    mobileUrl : `../../img/model-3.jpg`,
    tableUrl : `../../img/table-model-3.jpg`,
    dcUrl : `../../img/model-dc-3.jpg`,
  },
  {
    name : 'Overalls',
    price : '$ 160',
    category : 'firstpage',
    color : ['#3B6392', '#B0C3C7', ' #BFC3C8'],
    size : ['XS', 'S', 'M', 'L', 'XL'],
    mobileUrl : `../../img/model-4.jpg`,
    tableUrl : `../../img/table-model-4.jpg`,
    dcUrl : `../../img/model-dc-4.jpg`,
  },
  
  // {
  //   name : 'Jacket',
  //   price : '$ 40',
  //   category : 'catalog',
  //   color : [],
  //   size : [],
  //   mobileUrl : `../../img/catalogImg/catalog-jacket-1-mobile@1x.jpg`,
  //   tableUrl : `../../img/catalogImg/catalog-jacket-1-mobile@2x.jpg`,
  // },
  // {
  //   name : 'Jacket',
  //   price : '$ 70',
  //   category : 'catalog',
  //   color : [],
  //   size : [],
  //   mobileUrl : `../../img/catalogImg/catalog-jacket-2-mobile@1x.jpg`,
  //   tableUrl : `../../img/catalogImg/catalog-jacket-2-mobile@2x.jpg`,
  // },
  // {
  //   name : 'Jacket',
  //   price : '$ 60',
  //   category : 'catalog',
  //   color : [],
  //   size : [],
  //   mobileUrl : `../../img/catalogImg/catalog-jacket-3-mobile@1x.jpg`,
  //   tableUrl : `../../img/catalogImg/catalog-jacket-3-mobile@2x.jpg`,
  // },
  // {
  //   name : 'Jacket',
  //   price : '$ 50',
  //   category : 'catalog',
  //   color : [],
  //   size : [],
  //   mobileUrl : `../../img/catalogImg/catalog-jacket-4-mobile@1x.jpg`,
  //   tableUrl : `../../img/catalogImg/catalog-jacket-4-mobile@2x.jpg`,
  // },
  // {
  //   name : 'Jacket',
  //   price : '$ 160',
  //   category : 'catalog',
  //   color : [],
  //   size : [],
  //   mobileUrl : `../../img/catalogImg/catalog-jacket-5-mobile@1x.jpg`,
  //   tableUrl : `../../img/catalogImg/catalog-jacket-5-mobile@2x.jpg`,
  // },
  // {
  //   name : 'Jacket',
  //   price : '$ 40',
  //   category : 'catalog',
  //   color : [],
  //   size : [],
  //   mobileUrl : `../../img/catalogImg/catalog-jacket-6-mobile@1x.jpg`,
  //   tableUrl : `../../img/catalogImg/catalog-jacket-6-mobile@2x.jpg`,
  // },
  // {
  //   name : 'Jacket',
  //   price : '$ 110',
  //   category : 'catalog',
  //   color : [],
  //   size : [],
  //   mobileUrl : `../../img/catalogImg/catalog-jacket-7-mobile@1x.jpg`,
  //   tableUrl : `../../img/catalogImg/catalog-jacket-7-mobile@2x.jpg`,
  // },
  // {
  //   name : 'Jacket',
  //   price : '$ 35',
  //   category : 'catalog',
  //   color : [],
  //   size : [],
  //   mobileUrl : `../../img/catalogImg/catalog-jacket-8-mobile@1x.jpg`,
  //   tableUrl : `../../img/catalogImg/catalog-jacket-8-mobile@2x.jpg`,
  // },
  // {
  //   name : 'Jacket',
  //   price : '$ 85',
  //   category : 'catalog',
  //   color : [],
  //   size : [],
  //   mobileUrl : `../../img/catalogImg/catalog-jacket-9-mobile@1x.jpg`,
  //   tableUrl : `../../img/catalogImg/catalog-jacket-9-mobile@2x.jpg`,
  // },
  

]


export const promoTemp = {
  description: 'Street fashion collection',
  title : 'Fall 2019',
  url : {
    mobile : "../../img/new-collection-mobile.jpg",
    tablet : "../../img/new-collection-tablet.jpg", 
    dcversion : "../../img/new-collection-dsk.jpg",
  }
}